-- ---------------------------------------------------------------------------
--  Yeni carinin ANA ADRES satiri. (ADR D-127)
--
--  Bu dosya da olculerek uretildi: sablon, adr_adres_no = 1 olan 1753 ana
--  adres satirindan alindi.
--
--  Neden ayri bir satir gerekiyor: CARI_HESAPLAR'da adres yok, orada sadece
--  cari_fatura_adres_no = 1 ve cari_sevk_adres_no = 1 isaretcileri var. O
--  isaretciler bu tabloda adr_adres_no = 1 olan satiri gosterir. Adres satiri
--  yazilmazsa cari acilir ama faturada adres bos kalir.
--
--  adr_RECno IDENTITY. adr_RECid_RECno insert aninda bilinemez; 0 yazilip
--  ayni islemde SCOPE_IDENTITY() ile guncellenir (bkz. CariWriter).
-- ---------------------------------------------------------------------------
INSERT INTO CARI_HESAP_ADRESLERI (    [adr_RECid_DBCno],
    [adr_RECid_RECno],
    [adr_SpecRECno],
    [adr_iptal],
    [adr_fileid],
    [adr_hidden],
    [adr_kilitli],
    [adr_degisti],
    [adr_checksum],
    [adr_create_user],
    [adr_create_date],
    [adr_lastup_user],
    [adr_lastup_date],
    [adr_special1],
    [adr_special2],
    [adr_special3],
    [adr_cari_kod],
    [adr_adres_no],
    [adr_aprint_fl],
    [adr_cadde],
    [adr_mahalle],
    [adr_sokak],
    [adr_Semt],
    [adr_Apt_No],
    [adr_Daire_No],
    [adr_posta_kodu],
    [adr_ilce],
    [adr_il],
    [adr_ulke],
    [adr_Adres_kodu],
    [adr_tel_ulke_kodu],
    [adr_tel_bolge_kodu],
    [adr_tel_no1],
    [adr_tel_no2],
    [adr_tel_faxno],
    [adr_tel_modem],
    [adr_yon_kodu],
    [adr_uzaklik_kodu],
    [adr_temsilci_kodu],
    [adr_ozel_not],
    [adr_ziyaretperyodu],
    [adr_ziyaretgunu],
    [adr_gps_enlem],
    [adr_gps_boylam],
    [adr_ziyarethaftasi],
    [adr_ziygunu2_1],
    [adr_ziygunu2_2],
    [adr_ziygunu2_3],
    [adr_ziygunu2_4],
    [adr_ziygunu2_5],
    [adr_ziygunu2_6],
    [adr_ziygunu2_7],
    [adr_efatura_alias],
    [adr_eirsaliye_alias]
) VALUES (
    0,
    0,
    0,
    0,
    32,
    0,
    0,
    0,
    0,
    :mikroKullanici,
    :simdi,
    :mikroKullanici,
    :simdi,
    '',
    '',
    '',
    :cariKod,
    1,
    0,
    :adres,
    :mahalle,
    '',
    '',
    '',
    '',
    :postaKodu,
    :ilce,
    :il,
    :ulke,
    '',
    '',
    '',
    :telefon,
    '',
    '',
    '',
    '',
    0,
    '',
    '',
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    '',
    ''
)
